# ---------------------------------------------------------------------------
# The outputs are the same names in both modes, so whatever consumes this module
# does not have to know which kind of database it got. try() is what makes that
# work: the branch that was not built has no index 0, and try falls through to
# the one that was.
# ---------------------------------------------------------------------------

output "endpoint" {
  description = "Host to connect to. The cluster writer endpoint for Aurora, the instance address otherwise."
  value       = try(aws_rds_cluster.this[0].endpoint, aws_db_instance.this[0].address)
}

output "reader_endpoint" {
  description = "Aurora only. Load balances read only connections across the readers. null for a standard instance."
  value       = try(aws_rds_cluster.this[0].reader_endpoint, null)
}

output "port" {
  description = "Port the database listens on."
  value       = local.port
}

output "database_name" {
  description = "Name of the database created inside the instance or cluster."
  value       = var.db_name
}

output "master_username" {
  description = "Master user name."
  value       = var.username
}

output "master_password" {
  description = "Master password, generated by the module unless one was passed in. Read it with terraform output -raw."
  value       = local.master_password
  sensitive   = true
}

output "identifier" {
  description = "Identifier of the cluster or of the instance, whichever was built."
  value       = try(aws_rds_cluster.this[0].cluster_identifier, aws_db_instance.this[0].identifier)
}

output "instance_identifiers" {
  description = "Every instance the module built. One entry for a standard instance, one per member for Aurora."
  value       = var.use_aurora ? aws_rds_cluster_instance.this[*].identifier : aws_db_instance.this[*].identifier
}

output "is_aurora" {
  description = "Which branch was taken. Useful in a caller that has to behave differently for a cluster."
  value       = var.use_aurora
}

output "security_group_id" {
  description = "Security group in front of the database. Reference it from the application security group instead of opening a CIDR range."
  value       = aws_security_group.this.id
}

output "subnet_group_name" {
  description = "Name of the DB subnet group."
  value       = aws_db_subnet_group.this.name
}

output "parameter_group_name" {
  description = "Name of the DB parameter group, the instance level one, attached in both modes."
  value       = aws_db_parameter_group.this.name
}

output "cluster_parameter_group_name" {
  description = "Aurora only. Name of the cluster level parameter group. null for a standard instance."
  value       = try(aws_rds_cluster_parameter_group.this[0].name, null)
}

output "engine_version" {
  description = "The version that was actually created, resolved from the prefix against the RDS API."
  value       = local.engine_version
}

output "parameter_group_family" {
  description = "Family the parameter groups were created with."
  value       = local.parameter_group_family
}
